openapi: 3.0.3

info:
  title: Ray Tracer API
  version: 1.0.0

paths:
  /render/image:
    get:
      summary: Render a ray traced image
      description: Returns a generated ray traced image as PNG
      operationId: renderImage
      parameters:
        - name: width
          in: query
          required: true
          schema:
            type: integer
            minimum: 100
            maximum: 1000
            default: 400
        - name: height
          in: query
          required: true
          schema:
            type: integer
            minimum: 100
            maximum: 1000
            default: 400
        - name: samplesPerPixel
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 300
            default: 100
      responses:
        "200":
          description: Rendered image
          content:
            image/png:
              schema:
                type: string
                format: binary